### ISSUE TITLE
Incorrect Firefox shadow

### ISSUE THREAD

**Issue by equeim** [chjj/compton#201]
http://itmages.ru/image/view/1703425/7bf40d74
http://itmages.ru/image/view/1703800/2554c05a
Of course, I can disable shadows for Firefox, but it is ugly when all programs have shadows while Firefox doesn't.

**Comment by marioortizmanero** [comment]
Quick update: if you're going to use `"class_g = 'Firefox' && !window_type *= 'menu'"`, please note that it may be lowercase `firefox` instead. They might have changed the class name.

**Comment by cubetastic33** [comment]
How do I disable shadows for Firefox Nightly? `"class_g = 'Firefox' && !window_type *= 'menu'"` doesn't seem to be working, and I don't know how to figure out the class name

**Comment by Kr1ss-XD** [comment]
> I don't know how to figure out the class name

@cubetastic33 - You can use the `xprop` tool in order to do so. After launching click into the window in question, and you'll get the window properties as output.

One of these is an array called something like `_WM_WINDOW_CLASS` or `_WM_CLASS` (with or without the leading underscore) consisting of two string values, the later of which is the window "class". (The former one is the "instance", btw.)

**E/** A simple `xprop WM_CLASS` followed by a click into the window should give you _only_ the output you need.

**Comment by cubetastic33** [comment]
Ah, thanks!

**Comment by Kzinux** [comment]
`class_g = 'Firefox' && !window_type *= 'menu'` also disable the shadow of firefox main window.
Change it to `"class_g = 'firefox' && window_type = 'utility'"` will only exclude tooltip menu.

**Comment by OJFord** [comment]
The default system-wide configuration includes some `shadow-exclude`s, maybe one of these for Firefox should be in there too?
