### ISSUE TITLE
Can't get compton to log from script?

### ISSUE THREAD

**Issue by moulei** [chjj/compton#263]
Hi richardgv,

I have a compton script I'm trying to use;

```
#! /bin/bash
# compton level selector

if [ "$1" == "-s" ]; then
    killall compton
elif [ "$1" == "-l" ]; then
#   killall compton
    sleep 1s
    compton -b -cCfF -I20 -O10 -D1 -t-5 -l-5 -r4 -o.8 &
elif [ "$1" == "-f" ]; then
#   killall compton
    sleep 1s
    compton --config ~/.config/compton -b --logpath /tmp/compton.log &
else
    echo "compton Usage:"
    echo "-s = stop"
    echo "-l = light"
    echo "-f = full"
fi
```

If I run the script as; ```./.compton -f``` it won't create the compton.log in /tmp

I can't figure out why... Hmm

**Comment by richardgv** [comment]
Thanks for the report! The cause here is compton only redirects stdout and stderr after it forked, and it does not `fork()` when the parent PID of the process is already 1 (`init`), which happens in your case: The bash script quited before compton completes the initialization, thus the parent PID of the compton becomes 1 after the parent process went away. `3b17fe1` (in `richardgv-dev` branch right now) should fix the issue.

A workaround is to remove the trailing ` &` on the `compton` line in your script, by the way.

**Comment by moulei** [comment]
HI richardgv,

Ahh I was wondering about the trailing ```&```, should I remove it for both lines?

thanks

**Comment by richardgv** [comment]
You could. `&` is (usually) not needed when you have `-b`.

Does my fix work for you, by the way?

**Comment by moulei** [comment]
Yes removing the ampersand seemed to of done it...

THANKS

**Comment by richardgv** [comment]
Thanks for the feedback. I actually meant whether the commit 3b17fe1 fixes your problem, though. :-D

**Comment by moulei** [comment]
Ahh the commit, no sorry didn't try that, just removed the ampersand...

thanks
