### ISSUE TITLE
Uncomment icon in compton.desktop

### ISSUE THREAD

**Issue by codehearts** [chjj/compton#290]
There's an Icon line compton.desktop that specifies the icon as "xcompmgr", but it's commented out. Is there a reason this is commented, and is there a reason for specifying "xcompmgr" rather than "compton"? Could this line be changed to `Icon=compton`?

**Comment by kelleyk** [comment]
I don't see an icon named `compton` in any of the pacakges or source repositories that I have mirrored.

The relevant spec (http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) says that if the value of `Icon` is not an absolute path, it is resolved as described in the icon theme spec (http://freedesktop.org/wiki/Specifications/icon-theme-spec/).

There are some nuances, but the upshot is that changing the line as you suggest would make software that wanted an icon look for one of `compton.{png,svg,xpm}`, which it would't find.  (I'm not aware that an icon for `compton` even exists.)

If the desktop file is specifying `xcompmgr`'s icon, that's probably because compton is a fork of a fork of `xcompmgr`.

(And, out of curiosity: why do you want an icon, anyhow?  Aren't you just starting `compton` automatically when your X session starts?)

**Comment by nejsan** [comment]
I am starting compton automatically with X. I was just curious because the .desktop file adds an entry to an applications menu I occasionally use and the blank icon for compton bothered me enough to see if it would be easy to fix.

From an older issue, it sounds like the .desktop file was added for certain use cases, so removing it isn't appropriate. I know that compton doesn't provide its own icon, but it's possible for other open source icon sets to provide that. I could also try to contribute a default compton icon to this project.

**Comment by kelleyk** [comment]
Neat; I was only trying to explain why the change wouldn't have done anything.  I don't see `xcompmgr.png` anywhere in the Ubuntu 15.04 repositories, either, which is why you've got a blank icon, but I see some references to one in an older, RedHat-family package named `xcompmgr-tools`. 

I'm not this repository's maintainer, but if there were a pull request open, I'd pull the commit into what I package :)

**Comment by richardgv** [comment]
The `Icon=` line was commented out because we don't actually have one and OBS does not like an icon that does not exist in `compton.desktop`. See #134. I would be grateful if somebody could provide a suitable fallback icon without issues in license for compton so that I could safely enable it.

I used `Icon=xcompmgr` because I thought `xcompmgr` has a higher chance of having an icon in third-party icon sets... Although I have not seen any so far.
