### ISSUE TITLE
'rough' transperency

### ISSUE THREAD

**Issue by LeonardKoenig** [chjj/compton#296]
I do not know how to say this as I have no experience with such - and I could imagine there being an easy solution but I can't find it as I don't know what to search for. So here are some illustrating screenshots:
![image](https://cloud.githubusercontent.com/assets/7831843/8810940/c2c6f14e-2ff2-11e5-9cb8-09180700e666.png)
![image](https://cloud.githubusercontent.com/assets/7831843/8810942/c5ac4f9e-2ff2-11e5-8b97-d123bdddc935.png)

first with transperency, second without.
Except the obvious difference of the brightness, first picture also shows 'stepped' rather than gradually changing colors. Is there a setting for 'HQ'-opacity?

**Comment by onodera-punpun** [comment]
It's called banding, and probably impossible to fix with compton. You can probably fix it yourself by adding a really tiny bit of noise to your wallpaper with gimp or ps.

**Comment by kelleyk** [comment]
@LeonardKoenig, I'm not sure that I understand exactly what we're looking at.  This is an image you're displaying while running compton with (first, darker image) and without (second, lighter image) transparency?

**Comment by LeonardKoenig** [comment]
@kelleyk Yep, it's my background image. The second has a (semi-transparent) window over it. This effect is called 'banding' as @onodera-punpun told me - thanks for that!
If it's really impossible to fix in compton, I will close this issue ofcourse. Will try the idea with the noise in GIMP though!

**Comment by onodera-punpun** [comment]
@LeonardKoenig I'm not a programmer but a graphics person so I don't *really* know if it's unfixable, however I think it is highly unlikely.

Here is an example I made in gimp:
* 1 https://sr.ht/De-B.png - The wallpaper with a black layer above it at 65% opacity, like you can see it gives gives the same banding effect as your compton example.
* 2 https://sr.ht/9tpt.png - I added a tiny bit of noise to the wallpaper.
* 3 https://sr.ht/wioG.png - The noisy wallpaper from above with a black 65% opacity layer above it, noticeably less banding

**Comment by kelleyk** [comment]
@onodera-punpun To clarify, these examples are completely synthetic (made in GIMP) and were not produced by `compton`?

I suspect that the problem is that this image is only using 8 bits (and thus 256 steps) per channel.  The source image is about rgb(39, 76, 93) just below the blue-and-grey object and rgb(43, 43, 43) in the lower-left corner, which is about 40 steps; this is enough that you don't see banding.

Now multiply all of that by 0.35 (what's left over from your 65%-opaque black overlay), and remember to round to the nearest integer!  Now every group of three steps is combined into a single one, and there are only about ten bands; this is why you notice it.

The noise isn't fixing the underlying problem, but it *does* make it much less noticeable to the eye.  I bet that the problem would also go away if you converted the image to use 16 bits per channel before you added your black layer.

**Comment by LeonardKoenig** [comment]
Wow, thanks for all the input - I have learned much more today ^^
Found this nice explanation also commenting on banding in the end:
https://userbase.kde.org/Krita/Manual/ColorManagement

The problem now: Well, Krita can handle 16-bit per channel - but nothing else can :D - not even GIMP!
GIMP 2.9 will have rudimentary support, completing it in 3.0.
Sadly it seems that feh does not have support for 16-bit/channel png's so I get this result:
![image](https://cloud.githubusercontent.com/assets/7831843/9245264/dc6f726c-41a2-11e5-96ff-bcbbc534d637.png)

*without* a filter applied, just exported as 16-bit. Even gwenview does not like it and gives the same result. Maybe I now find a wallpaper-program which supports 160bit color channel ... but I doubt I will be successfull as 8bits per pixel is usually the highest monitors support.

But as it is confirmed to be not really a compton-problem I will close this issue - but you can ofcourse feel free to add something if you want :-)
