### ISSUE TITLE
`--unredir-if-possible` not unredirecting fullscreen windows

### ISSUE THREAD

**Issue by Mocha-Bean** [chjj/compton#318]
As far as I can tell, fullscreen windows are not being unredirected. Games in which I have disabled vsync are being vsync'ed. I assume compton is doing this, as when I kill compton, the issue disappears.

OS: Arch Linux
Kernel: x86_64 Linux 4.2.3-1-ARCH
DE: XFCE4
WM: Xfwm4
CPU: Intel Core i5-4460 CPU @ 3.4GHz
GPU: GeForce GTX 970

GPU Driver: nvidia 355.11-3 (from Arch repos)

~/.compton.conf: http://pastebin.com/rBiqMJzx

**Comment by Jemi** [comment]
I'm having an issue with poorer than expected benchmark performance, which I had thought was caused by compton not redirecting windows. I did a little debugging with GDB and found something that might (hopefully) be useful. I set a breakpoint on line 1246 in the git source (unredir_possible = true;) and it broke on that line after I ran 'phoronix-test-suite benchmark unigine-valley' and I had to kill gdb from a console window to unfreeze my screen (and yes, I verified by looking at the gdb output that it broke). Then I found a reference to DEBUG_REDIR in the source. I set it this way:

$make clean
$CFLAGS="-ggdb -DDEBUG_REDIR" make

and then I ran:

$./compton

and in another terminal:

$phoronix-test-suite benchmark unigine-valley (and selected 1080p fullscreen)

After escaping from the benchmark tool (which ran twice), I looked at the output on the terminal running compton:

 ./compton
init_overlay(): overlay = 0x000001d9
[     0.09 ] redir_start(): Screen redirected.
[    33.02 ] redir_stop(): Screen unredirected.
[    45.03 ] redir_start(): Screen redirected.
[    54.72 ] redir_stop(): Screen unredirected.
[    62.53 ] redir_start(): Screen redirected.

So it *was* being redirected, or at least compton believed it was. I'm going to assume it was telling the truth for now. Anyway, you should definitely verify that compton is not redirecting by taking these steps:

$git clone https://github.com/chjj/compton.git
$cd compton
$CFLAGS="-ggdb -DDEBUG_REDIR" make
$./compton

and then run a game in fullscreen mode. I don't know how vsync fits into all of this, but it doesn't seem to me that vsyncing alone is proof that compton is not redirecting. Compton still runs even when it's redirected, it just doesn't buffer (composite) anything while it is. It still has to have its environment ready for when it comes out of redirect mode, and that could be triggering games to turn off their vsync. It could also be doing something else that results in FPS throttling, which makes it appear that the games are vsynced. For this reason, you should definitely verify that it's not redirecting. I spent the last several hours just *sure* that compton wasn't redirecting, until I finally figured out that there was an easy way to actually verify it (and of course this needs to be documented somehow, like in the README file for example). Anyway, good luck. I'm off to go figure out what's *actually* throttling my brand new GTX 970 GPU.

**Comment by Mocha-Bean** [comment]
Oh, I forgot to update this.

The issue occurred with a "stable" version 0.1_beta2-5 (https://aur.archlinux.org/packages/compton/).

I switched to compton-git (https://aur.archlinux.org/packages/compton-git/) and the problem was fixed.
