### ISSUE TITLE
Snap-to Grid

### ISSUE THREAD

**Issue by quequotion** [chjj/compton#327]
Just an idea for the dbus backend.

A feature I like very much in compiz is the Grid plugin. I have custom settings for this: each corner makes a window fill the corner (one quarter) and each side fills that side (one half, horizontal or vertical). It seems like this could be done in a 2d-friendly way.

Are there xorg tools to get the window position and remap to x,y;x,y? Or interface with compton to do it?

**Comment by kelleyk** [comment]
Keep in mind that Compiz is both a compositor and a window manager.  The functionality that you're describing is part of the window manager half, whereas `compton` is a compositor.

If you want to add this behavior to your desktop environment, you might try `wmctrl`; for example, I have my window manager set up so that several key bindings trigger various invocations of `wmctrl` to resize or move windows.

**Comment by quequotion** [comment]
How about a way to implement hot corners/edges?
This feels best when it can be done by drag and drop.

**Comment by kelleyk** [comment]
This is not relevant to `compton`.

**Comment by garnetius** [comment]
These features belong to window manager (Like Openbox), not compositing manager (which compton is). There are some compositors which simultaneously act as window managers, but this is not the case with compton.

**Comment by quequotion** [comment]
This is overdue for closing; I agree it makes more sense to do this with a window manager. I don't know if wmctrl supports hot corners/edges, but that's something I'll have to look into elsewhere.
