### ISSUE TITLE
Failed to get glXWait/GetVideoSyncSGI function

### ISSUE THREAD

**Issue by kulkarnih** [chjj/compton#372]
This is more of a question than an issue. I'm trying to get transparent backgrounds in my gnome-terminal while using i3. I'm running Ubuntu 16.04 on Virtual box.

This is the compton command I'm running, `compton --vsync opengl --backend glx --paint-on-overlay --config ~/.compton.conf`.

I get this error `vsync_opengl_init(): Failed to get glXWait/GetVideoSyncSGI function.`.

I am using the VBox guest addition driver for my graphics card.

**Comment by richardgv** [comment]
`--vsync opengl` asks compton to use GLX extension `SGI_video_sync` for VSync, and the message generally indicates the extension is not found. You will not be able to use the VSync method in the case.

If you are not experiencing tearing, there is no need to use `--vsync`. If you need `--vsync` because compton repaints too much and causes a performance issue, use `--sw-opti` instead.

If you are experiencing tearing issues, you could try other VSync methods. See the `--vsync` section in the`--help` message or the man page for more details. Generally `--vsync=opengl-swc` is preferred for the GLX backend.

If you need to use `--vsync=opengl` for some reasons, please show us the output of `glxinfo`. It is a part of the `mesa-utils` package.

**Comment by hariprasadkulkarni** [comment]
Without vsync, I get this error.

`vsync_opengl_swc_init(): Failed to get SGI_swap_control function`


This is the glxinfo output

`$ glxinfo
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: Chromium
server glx version string: 1.3 Chromium
server glx extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
client glx vendor string: Chromium
client glx version string: 1.3 Chromium
client glx extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
GLX version: 1.3
GLX extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
OpenGL vendor string: Humper
OpenGL renderer string: Chromium
OpenGL version string: 2.1 Chromium 1.9
OpenGL shading language version string: 4.00 - Build 9.17.10.3062`
