### ISSUE TITLE
Compton kills xserver when using i3lock

### ISSUE THREAD

**Issue by amuttsch** [chjj/compton#373]
Hi,

I'm using Arch Linux (Kernel 4.7.1) with i3, i3lock and compton `compton-0.1_beta2.5-3` on xorg-xserver 1.18.4-1. Sometimes when locking the screen using `i3lock`, the xserver just quits and I'm back on the console. No logs, no error messages, nothing.

After some digging I uninstalled compton and I couldn't reproduce this issue anymore. After reinstalling it, the problem occurs again.

Are there any logs from compton that I can check? What else can I do to help further investigating this issue?

Thanks!

**Comment by richardgv** [comment]
Well, I hope the reply is not too late. Since you are thrown back to the console after X quits, I suppose you are using `xinit` (or `startx`) to start X? In which case, there are two possibilities I know that may cause the issue:

* The execution of `xinitrc` completes. Since typically the WM is executed on foreground on the last line of `.xinitrc`, generally it means i3 quits.

* X server quits, probably because of a crash.

So my suggestions are:

* Show us the log of X server after reproducing the issue. It is probably `/var/log/Xorg.*.log`, `~/.local/share/xorg/*.log`, or at somewhere else depending on your configuration. You could see whether X server quit normally or crashed from the log.
* Show us the output of `xinit`, `startx`, or your display manager after reproducing the issue. It may be printed on stdout/stderr on the console you launched it, or redirected/saved somewhere (`~/.xsession-errors`?) depending on your configuration. It may show us how i3 quitted.

	* If you launch i3 with `exec i3` in `.xinitrc`, try removing the `exec`, as the shell may print a message when i3 is killed by a signal (e.g. SIGSEGV) if `exec` is not used.

* It might be helpful if you enable logging in i3 after reproducing the issue. See the [the official documentation](https://i3wm.org/docs/debugging.html) for instructions.

Also, does the issue occur immediately after i3lock is launched, or a while later (e.g. when the screen is turned off)?

By the way, you may wish to check if the issue is still reproducible if you use `compton --config /dev/null` to launch compton.

**Comment by amuttsch** [comment]
Sorry for the late reply, I managed to get it working. I installed version `0.1_beta2.83.g2343e4b-1` from the [arch aur](https://aur.archlinux.org/packages/compton-git/) and the problem is gone. So something between those versions fixed the probem.

Thanks for your help, I'll close this now.
