### ISSUE TITLE
inactive-opacity and inactive-dim

### ISSUE THREAD

**Issue by alecive** [chjj/compton#392]
Hello, I am trying to have some way to discern between active and inactive windows. I tried setting both `inactive-opacity` and `inactive-dim` to `0.2`, but nothing happens to inactive windows at all. Is there something else I need to fiddle with to make this work?

FYI, I am running Ubuntu 14.04 with `bspwm`as a window manager.

**Comment by fleutot** [comment]
Are you sure `compton` uses your config file at all?

**Comment by richardgv** [comment]
* Many options of compton causes it to treat inactive windows as active: Notably, `--mark-ovredir-focused` causes all application windows to be considered focused with bspwm, because of how bspwm manages windows. `--mark-wmwin-focused`, `--focus-exclude`, `--detect-transient`, and `--detect-client-leader` may cause certain inactive windows to be treated as active.

* `--use-ewmh-active-win`changes how compton determines the active window. In my tests compton work with or without the option on bspwm-0.9.2, but it does not hurt to try enabling/disabling it.

* If none of the ideas above help, you could try running compton with  `compton --config /dev/null -i 0.8 --inactive-dim 0.2`, to see if it is a problem that the configuration file did not take effect, or was broken by some other options.

**Comment by alecive** [comment]
@richardgv the issue was the first one. Setting `mark-ovredir-focused = false;` in the config file solved the problem.

So now my question is: what that option does exactly? In the description it says: "Mark all non-WM but override-redirect windows active (e.g. menus)", but it didn't seem to have a difference on menus at all - or at least that is what it seems.

**Comment by alecive** [comment]
Also, I am not experiencing any blurring of transparent windows, even though I set it in the config file:

```bash
# Blur background of transparent windows. Bad performance with X Render backend. GLX backend is preferred.
blur-background = true;
# Blur background of opaque windows with transparent frames as well.
blur-background-frame = true;
# Do not let blur radius adjust based on window opacity.
blur-background-fixed = false;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];
```

**Comment by avahe-kellenberger** [comment]
I also had to use `mark-ovredir-focused = false;` for inactive windows to have transparency - this seems rather odd. Is this normal/expected behavior?

@alecive to get blurring I had to call compton with the argument `--blur-method kawase` and make sure it was pointed at my config file
