### ISSUE TITLE
Certain windows shadow distance incorrect.

### ISSUE THREAD

**Issue by calexil** [chjj/compton#397]
not sure what's going on here, but certain windows and dialogues in mint mate 18 have an extra wide window shadow.

Marco+compton

[Configuration can be found here](http://dpaste.com/1K7SK2Y)

![](https://cloud.githubusercontent.com/assets/3487071/17498246/33c0f582-5d94-11e6-9f60-923047baabb1.png)

**Comment by fleutot** [comment]
This is the same ass [this issue](https://github.com/chjj/compton/issues/189). The answers there didn't help me much, but give it a shot:

```
shadow-exclude = [
    "_GTK_FRAME_EXTENTS@:c"
 ];
```
Your problem has probably to do with a new release of GTK, though.

What did help me is to modify my GTK config so that it doesn't drop shadows, since compton is in charge of that anyway:

In `~/.config/gtk-3.0/gtk.css`:
```
.window-frame {
     box-shadow: none;
     margin: 0;
     border-style: none;
     border-radius: 0;
 }
```
The most relevant parameter is `box-shadow`, but `border-radius` might be interesting since you may get black sharp corners instead of round ones anyway.

Another way would be to let GTK manage shadows, and disable them for compton.

**Comment by calexil** [comment]
good catch, any idea how to fix it without totally disabling shadows, so they still work just without the double border?

**Comment by fleutot** [comment]
I don't think it's possible. If I understand correctly, GTK draw a shadow and compton thinks this shadow is part of the window, and draws its shadow around it. Why would you want both the GTK shadow and the compton shadow at the same time anyway?

**Comment by richardgv** [comment]
As stated by fleutot, you could choose to disable the shadow from either compton or GTK+. Generally the former is preferred.

With gtk+-3.22.4 + Adwaita, I am able to avoid compton drawing shadows for the problematic windows with `--shadow-exclude '_GTK_FRAME_EXTENTS@:c'`. The rule has been a part of `compton.sample.conf` since 9a99e7a0 (Apr 2014), but it is not a part of your configuration.

If it is not effective for you, please tell us about your version of GTK+, your GTK+ theme, and the output of `xprop` after you run the command and click on a window with the problem, to allow us to better diagnose the issue.

**Comment by calexil** [comment]
here you go:
![calc](https://cloud.githubusercontent.com/assets/3487071/21404196/0660eab6-c78e-11e6-9753-f777be8636e3.png)

[heres the output of xprop](http://dpaste.com/1JZHSSM)

more system info:

![gtketc](https://cloud.githubusercontent.com/assets/3487071/21404207/196dee56-c78e-11e6-9d59-ef4dd2085b39.png)

**Comment by richardgv** [comment]
@calexil:

Your xprop output shows your GTK+ sets the property `_GTK_FRAME_EXTENTS` on windows with shadow rendered by it, so the shadow exclusion rule should work. I also tried starting compton with the exclusion rule, together with gtk+-3.22.4, marco-1.16.0, and gnome-calculator-3.22.2, and the rule effectively prevented compton from drawing shadow for the gnome-calculator window. It proves most likely there is no marco-specific problem that breaks the rule.

Could you please check if running compton with the following command prevents it from drawing shadow on gnome-calculator?

```sh
compton --config /dev/null -cz --shadow-exclude '_GTK_FRAME_EXTENTS@:c'
```

If it works, please check if you have added the shadow exclusion rule to your configuration file correctly; If it does not work, please tell us the version of your compton (`compton -h | head -n1`), and I will consider other possibilities and provide further instructions to diagnose it.

**Comment by calexil** [comment]
issue persists, only default shadow settings comply with MATE

**Comment by calexil** [comment]
wontfix

**Comment by calexil** [comment]
resolved with the lines:

shadow-exclude = [
 "_GTK_FRAME_EXTENTS@:c",

in ~/.config/compton.conf
