### ISSUE TITLE
"Flickering" when opening a new window or tooltip on a maximized window.

### ISSUE THREAD

**Issue by Dav1605** [chjj/compton#402]
Here is a video of he issue (Only used tooltips but the same happens when opening any application):
https://streamable.com/1i7sk

When opening a new windows or a tooltip in a maximized window, it does flick before appearing. If you do the same with the windows no-maximized, even if it cover all the screen, it doesn't happen. Also doesn't happen if you do it when the focus is on another no maximized window (Like the last example on the video)

I am using Arch Linux with OpenBox and Arc Theme. GPU is a RX 480 using AMDGPU drivers.
I have tried all Vsync options, xrender, glx, and a lot of other options without any effect.

Using this fixes the problem `compton --config /dev/null -f -D 50`
But I need other effects too.

**Comment by 0x041E** [comment]
This seems like it has to do with `unredir-if-possible-delay` because it defaults to 0 so fullscreen windows are immediately unredirected which causes the flicker i reproduced this by having the default value (0) of unredir-if-possible-delay. You can work around it by increasing the value of unredir-if-possible-delay. I use unredir-if-possible-delay = 1000 (1 second until window unredirection). If you set delay to length of your fading animation it should not flicker anymore

**Comment by Dav1605** [comment]
Thank you @0x041E that fixed the problem sorry I forgot to update
