### ISSUE TITLE
very laggy dragging windows [i3-gaps]

### ISSUE THREAD

**Issue by JarrColl** [chjj/compton#440]
Platform: Linux mint 18.1 amd64 -

GPU, drivers, and screen setup: <!-- Example: NVidia GTX 970, nvidia-375, single monitor

Compton version: <!-- 0.1~beta2-1 from the official repository

### Steps of reproduction

Open Factorio in steam and then open a window in floating mode then drag it around with $mod and mouse.

### Current Behavior & Other details
The window is extremely laggy (it only moves to the mouse location every few seconds and xorg cpu usage becomes very high. But if I exit compton it does not lag. I have tried to exclude Factorio in my compton.conf but it didn't work.

#####CONFIG FILE#####

https://pastebin.com/5giZ2zHA

**Comment by JarrColl** [comment]
i have solved the problem by using someone elses config file.
https://pastebin.com/0azLvSjb
I havent looked into why this solves the issue yet.

**Comment by jeroeness** [comment]
I have the same issue when dragging floating windows in general. The solution for me seems to be borderless floating windows, since redrawing the borders of floating windows is quite slow for some reason... I configured this in my i3 config `new_window none` or when you make a window floating: `border none`. I did not have to make any changes in my compton config file to fix this. For now the window dragging is smooth (but unfortunately not as smooth as scrolling on webpages).
