### ISSUE TITLE
Using the GLX backend causes lag when dragging windows

### ISSUE THREAD

**Issue by ghost** [chjj/compton#441]
Platform: Fedora 26 Workstation AMD64

GPU, drivers, and screen setup: AMD R7 370, default open source drivers from Fedora, two monitors side-by-side.

Compton version: git-v0.1_beta2-87-g316eac0-2017-04-30 (just cloned today)

Compton configuration: https://pastebin.com/vKnsNTVn

### Steps of reproduction

Running Compton on XFCE4 (haven't tried another DE) with the GLX backend (with or without the provided config file).

### Expected behavior

Moving windows shouldn't have any lag.

### Current Behavior & Other details

Moving windows makes the window lag slightly behind the cursor. Funnily enough, this only happens when moving the window slowly. Moving it quickly has no lag.

I know people have been asking this for literally years, and I've tried all the troubleshooting steps. The GLX backend is what's causing the lag. I ran compton with no config file and only the GLX backend and that caused it to lag. Running with the XRender backend causes lag.

I understand that using XRender is technically a fix, but I really need GLX for the vsync. Is there any way to stop the window lag?

**Comment by user827** [comment]
Maybe it's the same issue I had with amd open source drivers, but in my case the lag was very noticeable to me even when moving the cursor fast.  I got it fixed though by changing glFlush to glFinish just after glXSwapBuffers in https://github.com/chjj/compton/blob/316eac0613bf342ff91cc645a6c3c80e6b9083fb/src/compton.c#L2038. This fix also requires mesa with this commit: https://cgit.freedesktop.org/mesa/mesa/commit/?id=91c93dec980dbf7b253c124b85dc4e46d2a83587.

I have no experience with opengl but got the idea from here:
https://www.khronos.org/opengl/wiki/Swap_Interval
> "My rendered objects lag behind the mouse cursor, but only when Vsync is enabled!" You probably have several frames queued up in the GPU. You may want to consider calling glFinish.

I think when opengl-swc is on, glXSwapBuffers can be called multiple times to queue multiple frames before the function has to block and wait for a vblank to show one of them. Maybe the lag is there because the last frames in the queue are already quite old by the time they are seen.  With glFinish the cpu waits until swapbuffers has actually finished executing so the queue cannot fill up...  But this doesn't explain why glFinish before glXSwapBuffers doesn't seem to do anything though.

Btw I don't have any lag with GLX backend if vsync is off. Mesa enables opengl-swc automatically though unless you have vblank_mode <= 1 in drirc or environment.

**Comment by devmgran** [comment]
Hello! I too use Compton with the open source AMD drivers. For the longest time, Compton was merely something I'd tolerate because it seemed to somewhat eliminate screen tearing when watching videos, but the very noticeable lag that occured when dragging windows was always very bothersome for me (never encountered such issues when using Compiz, Kwin, etc, so it was very perplexing for me!) However, I recently found a solution whilst perusing the web.

On the MX Linux forums, a user known as "colin_b" shared his startup command for Compton (System Settings > Session and Startup > Application Startup; no compton.conf will be necessary for this!):
compton --backend glx --unredir-if-possible --glx-no-stencil --glx-no-rebind-pixmap --glx-swap-method buffer-age --vsync opengl-swc

This startup command has made Xfce the perfect desktop for me--again! ;D Hope all works out for you, OP.

**Comment by ghost** [comment]
Sorry it took me so long to get back to this thread, life suddenly got crazy for me =P

@devmgran Unfortunately, I still had the lag issue when I ran with those startup commands.

@user827 I'll be recompiling Mesa as soon as I can, and I'll get back to out to let you know what happens.

**Comment by ghost** [comment]
@user827 Unfortunately, that didn't fix the issue either.

**Comment by user827** [comment]
@PrimordialHelios 
I'd guess the lag has something to do with your dual screen setup. If you only need to prevent tearing, you could disable vsync completetely (vsync="none" and vblank_mode<=1) and turn on TearFree: https://wiki.archlinux.org/index.php/AMDGPU#Driver_options

**Comment by ghost** [comment]
Disabling the second monitor and restarting Compton doesn't change anything, and my card is too old (R7 370) for AMDGPU.

**Comment by user827** [comment]
@PrimordialHelios
Oh, I forgot. The older driver has TearFree too though: https://wiki.archlinux.org/index.php/ATI#Driver_options

**Comment by ghost** [comment]
@user827 Adding that caused my machine to hang after booting. I removed the file from a live USB I had, but I'll be pursuing this to see if I can figure out what happened. Thanks for pointing me in the right direction.

I'll be marking this as closed since it seems the only fix is to disable vsync, but I'll definitely post a fix if I ever come across one.

**Comment by ghost** [comment]
I know this is closed, but I recently tested the same config on my laptop with Intel graphics and whaddya know, same issue.

I'm starting to wonder if this is related to Fedora or XFCE/XFWM. I'll try testing that hypothesis out when I get the chance, and reopen if I find anything interesting.
